/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionModal01: typeof import('./components/customer/action-modal-01.vue')['default']
    ActionModal02: typeof import('./components/customer/action-modal-02.vue')['default']
    ActionModal03: typeof import('./components/customer/action-modal-03.vue')['default']
    ActionModal04: typeof import('./components/customer/action-modal-04.vue')['default']
    AutocompleteMultipleServer: typeof import('./components/@v/autocomplete-multiple-server.vue')['default']
    AutocompleteServer: typeof import('./components/@v/autocomplete-server.vue')['default']
    Confirm: typeof import('./components/@v/confirm.vue')['default']
    Countdown: typeof import('./components/@v/countdown.vue')['default']
    Currency: typeof import('./components/@v/currency.vue')['default']
    CustomerActionModal01: typeof import('./components/customer/action-modal-01.vue')['default']
    CustomerActionModal02: typeof import('./components/customer/action-modal-02.vue')['default']
    CustomerActionModal03: typeof import('./components/customer/action-modal-03.vue')['default']
    CustomerActionModal04: typeof import('./components/customer/action-modal-04.vue')['default']
    CustomerInquiry: typeof import('./components/customer/Inquiry.vue')['default']
    Date: typeof import('./components/@v/date.vue')['default']
    FilterForm: typeof import('./components/product/filter-form.vue')['default']
    Form: typeof import('./components/validate/form.vue')['default']
    Inquiry: typeof import('./components/customer/Inquiry.vue')['default']
    Modal: typeof import('./components/product/modal.vue')['default']
    ProductFilterForm: typeof import('./components/product/filter-form.vue')['default']
    ProductModal: typeof import('./components/product/modal.vue')['default']
    ProductTable: typeof import('./components/product/table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/product/table.vue')['default']
    Valert: typeof import('./components/@v/valert.vue')['default']
    ValidateForm: typeof import('./components/validate/form.vue')['default']
    VAutocompleteMultipleServer: typeof import('./components/@v/autocomplete-multiple-server.vue')['default']
    VAutocompleteServer: typeof import('./components/@v/autocomplete-server.vue')['default']
    VConfirm: typeof import('./components/@v/confirm.vue')['default']
    VCountdown: typeof import('./components/@v/countdown.vue')['default']
    VCurrency: typeof import('./components/@v/currency.vue')['default']
    VDate: typeof import('./components/@v/date.vue')['default']
    VValert: typeof import('./components/@v/valert.vue')['default']
  }
}
