/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LayoutsHeader: typeof import('./components/layouts/header.vue')['default']
    LayoutsNavigation: typeof import('./components/layouts/navigation.vue')['default']
    ProductAddModal: typeof import('./components/product/add-modal.vue')['default']
    ProductSearch: typeof import('./components/product/search.vue')['default']
    ProductTable: typeof import('./components/product/table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
